git clone git@github.com:IcyFlame/year-book-dav-2013.git
git clone git@github.com:IcyFlame/HTML-Learning.git
git clone git@github.com:IcyFlame/cows-and-bulls.git
git clone git@github.com:IcyFlame/VIPER5.git
git clone git@github.com:IcyFlame/note-taking.git
git clone git@github.com:IcyFlame/softwares-to-be-installed.git
git clone git@github.com:IcyFlame/VIPER41.git
git clone git@github.com:IcyFlame/stopwatch3.git
git clone git@github.com:IcyFlame/stopwatch2.git
git clone git@github.com:IcyFlame/stopwatch1.git
git clone git@github.com:IcyFlame/parse-cbse-result.git
git clone git@github.com:IcyFlame/git-automating-tasks.git
git clone git@github.com:IcyFlame/learning-js.git
git clone git@github.com:IcyFlame/VIPER4.git
git clone git@github.com:IcyFlame/VIPER3.git
git clone git@github.com:IcyFlame/VIPER2.git
git clone git@github.com:IcyFlame/VIPER1.git
git clone git@github.com:IcyFlame/Daily_diary2.git
